### ISSUE TITLE
maybe you can use bigint as the type of the number

### ISSUE THREAD

**Issue by Murat-Karakaya** [TJRelly/basic-calculator#1]
when you type: 9007199254740991+2 to the calculator, it gives me infinite.
to get the actual value it can run: Number(BigInt(9007199254740991)+BigInt(2))

If this explanation doesn't sounds clear, please let me know.

**Comment by TJRelly** [comment]
Thanks for the suggestion. 

It is supposed to be a basic calculator, so I don't expect people to use BigInts. However, if they do use one, I could throw some type of error. 

Do you have a suggestion on how to implement that?

**Comment by Murat-Karakaya** [comment]
Can I fork your repository? That way I can experiment, and maybe add Bigint int the counter.

**Comment by Murat-Karakaya** [comment]
Right now, I am not sure how to throw an error if the maximum size is exceeded. But I guess you can do something like:
```javascript
let a = 9007199254740991
let b = 2
if (BigInt(a+b) === BigInt(a)+BigInt(b)) {
       console.log("your answer: ", a+b)
}else {
       throw new Error
}



```

**Comment by Murat-Karakaya** [comment]
Hello, I found out that even scratch has this problem. I guess we can stop thinking about this small problem so both of us can have more time for big projects. It was nice meeting with you, take care :)

**Comment by TJRelly** [comment]
"Hello, I found out that even scratch has this problem." --- I'm not familiar with "scratch." Could you explain? 
Once again, thanks for all your help. Nice meeting you as well.

**Comment by Murat-Karakaya** [comment]
Scratch is a basic coding language to introduce someone to programming. [Here is the website](https://scratch.mit.edu/). In the coding section you can calculate simple math problems. And when you type the problem ``9007199254740991+2`` the code block returns ``9007199254740992`` . So yeah, they better fix that :D
